### ISSUE TITLE
Butterfly 0.05 + blueCFD: residuals? 

### ISSUE THREAD

**Issue by cyshimz** [ladybug-tools/butterfly-plus#5]
Hi again, I've not been able to get Butterfly working since my computer crashed last year and my hard disk was wiped. BlueCFD seems to be working really well so far and the installation process is truly a blessing compared to what I had to go through previously.

Has anyone else had problems with running the updated example files? I'm testing the indoor test case, but there are no residual values. The solution is not converging as well (up to time = 5000).

**Comment by tlpwka** [comment]
@DambronOlivier After changing that line,  `residual_values` outoup not "null", but zero, weird.
![capture](https://user-images.githubusercontent.com/47614656/53251314-a3b7e400-36bc-11e9-8741-7c68d78b71f6.PNG)
and:
![capture2](https://user-images.githubusercontent.com/47614656/53251327-aa465b80-36bc-11e9-9d8d-a1e2d16f2d78.PNG)

**Comment by mostaphaRoudsari** [comment]
@tlpwka try to purge the results and run it again. I just tested it locally and everything works fine. Also for outdoor study it will take some time before you get the first iteration finished and before that the values will be 0.
